- name: Reflect
  llm: ${sub|text_res}
  output_parser:
    name: StrParser
  max_steps: 1
  example: |
    Here is an example of reflection:
    Question: What is 2+2?
    Previous Attempts: 
    Attempt 1: 2+2 = 5
    Attempt 2: 2+2 = 3
    Reflection: Looking at my previous attempts, I made calculation errors. 
    The correct answer is 4 because when we add 2 and 2 together, we get 4.

- name: InputInterface 