- name: ThinkAction
  llm: ${sub|text_res}
  output_parser:
    name: StrParser
  max_steps: 10
  example: |
        Here are some examples:

        Question: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?
        Thought 1: I need to find the difference between the final and initial number of trees.
        Action 1: Search[initial and final number of trees]
        Observation 1: Initially there were 15 trees, and after planting there will be 21 trees.
        Thought 2: To find the number of trees planted, I need to subtract 15 from 21.
        Action 2: Lookup[21 minus 15]
        Observation 2: 21 - 15 = 6 trees were planted
        Thought 3: The grove workers planted 6 trees.
        Action 3: Finish[6]

        Question: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?
        Thought 1: I need to find the total number of cars after more arrive.
        Action 1: Search[cars in parking lot]
        Observation 1: There are 3 cars initially and 2 more cars arrive.
        Thought 2: The total number will be 3 plus 2.
        Action 2: Lookup[3 plus 2]
        Observation 2: 3 + 2 = 5 cars
        Thought 3: There are 5 cars in the parking lot.
        Action 3: Finish[5]

        Question: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?
        Thought 1: First, I need to find their total initial chocolates.
        Action 1: Search[total initial chocolates]
        Observation 1: Leah had 32 and her sister had 42, so 32 + 42 = 74 total chocolates.
        Thought 2: Now I need to subtract the eaten chocolates.
        Action 2: Lookup[remaining chocolates]
        Observation 2: 74 - 35 = 39 chocolates remain
        Thought 3: They have 39 pieces left in total.
        Action 3: Finish[39]

        Question: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?
        Thought 1: I need to find how many lollipops Jason gave away.
        Action 1: Search[lollipops given away]
        Observation 1: Jason had 20 lollipops and now has 12 lollipops.
        Thought 2: The difference will be the number given to Denny.
        Action 2: Lookup[lollipops difference]
        Observation 2: 20 - 12 = 8 lollipops
        Thought 3: Jason gave 8 lollipops to Denny.
        Action 3: Finish[8]

        Question: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?
        Thought 1: I need to find the total new toys from parents.
        Action 1: Search[new toys received]
        Observation 1: Shawn got 2 toys from mom and 2 toys from dad, so 4 new toys total.
        Thought 2: Now I need to add these to his initial toys.
        Action 2: Lookup[total toys]
        Observation 2: 5 initial toys + 4 new toys = 9 toys total
        Thought 3: Shawn now has 9 toys.
        Action 3: Finish[9]

        Question: There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?
        Thought 1: I need to find how many days computers were installed.
        Action 1: Search[installation days]
        Observation 1: Computers were installed from Monday to Thursday, which is 4 days.
        Thought 2: Now I can find total new computers.
        Action 2: Lookup[total computers added]
        Observation 2: 5 computers per day × 4 days = 20 new computers
        Thought 3: I need to add this to the initial number.
        Action 3: Lookup[final total]
        Observation 3: 9 initial + 20 new = 29 computers total
        Thought 4: There are now 29 computers.
        Action 4: Finish[29]

        Question: Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?
        Thought 1: I need to track the golf balls through each day.
        Action 1: Search[golf balls after Tuesday]
        Observation 1: After losing 23 on Tuesday, he had 58 - 23 = 35 golf balls
        Thought 2: Now I need to account for Wednesday's loss.
        Action 2: Lookup[final golf balls]
        Observation 2: After losing 2 more, he had 35 - 2 = 33 golf balls
        Thought 3: Michael had 33 golf balls at the end of Wednesday.
        Action 3: Finish[33]

        Question: Olivia has $23. She bought five bagels for $3 each. How much money does she have left?
        Thought 1: I need to find the total cost of bagels.
        Action 1: Search[bagel cost]
        Observation 1: Five bagels at $3 each costs 5 × $3 = $15 total
        Thought 2: Now I can find the remaining money.
        Action 2: Lookup[money remaining]
        Observation 2: $23 - $15 = $8 remaining
        Thought 3: Olivia has $8 left.
        Action 3: Finish[8]

        (Examples end)
  
- name: WikiSearch

- name: ReactOutput
