- name: Think
  llm: ${sub|text_res_stream}
  output_parser:
    name: StrParser

- name: Action
  llm: ${sub|text_res}
  output_parser:
    name: StrParser

- name: WikiSearch
  tool_manager:
    llm: ${sub|text_res}
    tools:
      - name: TavilyWebSearch
        tavily_api_key: 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 